### ISSUE TITLE
Week 5: Building

### ISSUE THREAD

**Issue by klinkoberstar** [uchicago-capp-30320/new-arrivals-chi#27]
BUGS
- [x] #38

UX/UI
- [x] #40 (Ongoing in to week 6)
- [x] #14 (Ongoing in to week 6)
- [x] #13 (Ongoing in to week 6)
- [x] #39
- [x] #52

FRONTEND:
- [x] #31 (Close without review pending new design)
- [x] #43 (Under Review)

BACKEND: 
- [x] #44 (Blocked, Maddie to discuss with Summer)
- [x] #32 (Ongoing in to week 6)

LOGIN PAGE

- [x] #45  (Ongoing into Week 6)
- [x] #46  (Ongoing into Week 6)

TESTING
- [x] #36 (Ongoing into Week 6)
- [x] #35

MISC TASKS
- [x] #37 
- [x] #41 (Under Review)
- [x] #29
